### ISSUE TITLE
commit 05a8ba808 breaks mingw/autoconf compilation

### ISSUE THREAD

**Issue by cron2** [OpenVPN/openvpn#885]
Hi,

I think mingw+autoconf should still work, but is broken after commit 05a8ba808

```
  CCLD     openvpnserv.exe
/usr/bin/x86_64-w64-mingw32-ld: openvpnserv-validate.o:validate.c:(.text+0x17b): undefined reference to `__imp_PathCchCanonicalizeEx'
```

because the new libraries (and possibly the new define) are only added/checked in the autoconf path.

@selvanair could you have a look?

**Comment by selvanair** [comment]
I usually moan when others break autotools build for Windows, and I broke it this time! Sorry.
See: http://gerrit.openvpn.net/c/openvpn/+/1334

**Comment by cron2** [comment]
Thanks.  This is a bit of nastiness, the mingw(64) shipped with ubuntu 22.04 does have the `pathcch.h` header, but no `libpathcch.*`, so it still fails.

Installing a 24.04 system right now to see what happens there.

**Comment by cron2** [comment]
ok, 24.04 is better

```
gert@ubuntu2404:~/mingw64/openvpn.git$ SU find / -name "*pathcc*"
/usr/x86_64-w64-mingw32/lib/libpathcch.a
/usr/x86_64-w64-mingw32/include/pathcch.h
/usr/i686-w64-mingw32/lib/libpathcch.a
/usr/i686-w64-mingw32/include/pathcch.h
/usr/share/mingw-w64/include/pathcch.h
```

and...

```
make[4]: Entering directory '/home/gert/mingw64/openvpn.git/src/openvpnserv'
  CC       openvpnserv-common.o
  CC       openvpnserv-interactive.o
  CC       openvpnserv-service.o
  CC       openvpnserv-validate.o
  CC       ../../src/openvpn/openvpnserv-wfp_block.o
  CCLD     openvpnserv.exe
```

**Comment by lstipakov** [comment]
I think for 2.7 we should either drop this (@lstipakov votes for it) or add to GHA / buildbot.
